"""Build the committed integer direction table for the geometry generator.

A ray at an integer number of degrees has an IRRATIONAL direction (Niven's theorem),
so we pre-round the direction vectors ONCE, offline, and commit them as data. Both
the Python oracle and the TypeScript production code read the identical committed
table at item-generation time; NEITHER evaluates a transcendental at runtime, which
is what makes the rendered SVG byte-for-byte identical across languages.

DIR[theta] = round_half_up(R*cos theta), round_half_up(R*sin theta)  for theta = 0..359,
on a large fixed radius R = 10000 (math convention: +x right, +y up; CCW degrees).

This script also AUDITS each committed entry with atan2 (the only place atan2 is ever
used) and asserts the recovered direction is within the published tolerance.

Run:  python oracle/build_dir_table.py
Writes: core/geometry/dir-table.json
"""

from __future__ import annotations

import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "core", "geometry", "dir-table.json")

R = 10000
AUDIT_TOL_DEG = 0.05  # committed entries must recover to within this (well under the +/-0.5 audit bound)


def round_half_up(x: float) -> int:
    """Round half up toward +infinity (matches gridRound on the exact rational)."""
    return math.floor(x + 0.5)


def main() -> int:
    table = []
    for theta in range(360):
        rad = math.radians(theta)
        dx = round_half_up(R * math.cos(rad))
        dy = round_half_up(R * math.sin(rad))
        table.append([dx, dy])

    # Audit (the only atan2 in the whole system): recovered angle must match theta.
    worst = 0.0
    for theta in range(360):
        dx, dy = table[theta]
        rec = math.degrees(math.atan2(dy, dx)) % 360.0
        err = min((rec - theta) % 360.0, (theta - rec) % 360.0)
        worst = max(worst, err)
        if err > AUDIT_TOL_DEG:
            raise AssertionError(f"theta={theta}: recovered {rec:.4f}, error {err:.4f} > {AUDIT_TOL_DEG}")
    # Cardinal directions must be exact.
    assert table[0] == [R, 0] and table[90] == [0, R] and table[180] == [-R, 0] and table[270] == [0, -R], table[:1]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    payload = {
        "comment": "GENERATED by oracle/build_dir_table.py. DO NOT EDIT. Integer ray directions at radius R; math convention (+y up, CCW degrees). Read identically by the Python oracle and the TypeScript production code; no runtime trig.",
        "R": R,
        "dir": table,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, separators=(",", ":"))
        fh.write("\n")

    # Emit an equivalent TypeScript module so the production code and the esbuild
    # bundle import the identical table without any JSON-import quirks.
    out_ts = os.path.join(ROOT, "core", "geometry", "dir-table.ts")
    body = ",".join(f"[{dx},{dy}]" for dx, dy in table)
    with open(out_ts, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by oracle/build_dir_table.py. DO NOT EDIT.\n")
        fh.write("// Integer ray directions at radius R; math convention (+y up, CCW degrees).\n")
        fh.write(f"export const R = {R};\n")
        fh.write(f"export const DIR: ReadonlyArray<readonly [number, number]> = [{body}];\n")

    print(f"Wrote {OUT} and {out_ts}: 360 entries, R={R}, worst audit error {worst:.5f} deg (<= {AUDIT_TOL_DEG}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
