"""Build the curriculum-review pack for the arithmetic-sequences generator.

Selects representative items covering every supported (task, mode, difficulty
band) combination and emits BOTH a machine-readable JSON pack and a
human-readable Markdown pack for the curriculum authority to review.

Each item records: seed, parameters, objective, mode, canonical answer, worked
solution, distractor rationales (with the named misconception), and the full
validation result. No item is marked approved/published — review is the gate
that advances lifecycle state, and only the curriculum authority does that.

Run:  python oracle/make_review_pack.py
Writes: docs/review/arithmetic_sequences_review_pack.{json,md}
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from spi_oracle import sequences as seq  # noqa: E402

REVIEW_DIR = os.path.join(ROOT, "docs", "review")
MISC_PATH = os.path.join(ROOT, "core", "misconceptions", "sequences.json")

# Supported (task, mode) combinations for the slice.
COMBOS = [
    ("nth_term", "multiple-choice"),
    ("nth_term", "integer"),
    ("sum_n", "multiple-choice"),
    ("sum_n", "integer"),
    ("find_d", "integer"),
    ("find_n_for_value", "integer"),
]
SCAN_LIMIT = 20000


def load_misconceptions() -> dict:
    lib = {m["misconceptionId"]: m for m in json.load(open(MISC_PATH, encoding="utf-8"))}
    return lib


def pick_representatives() -> list:
    """For each (task, mode), keep the first seed found per difficulty band."""
    buckets: dict = {}
    for task, mode in COMBOS:
        for seed in range(1, SCAN_LIMIT + 1):
            item = seq.generate(seed, {"task": task, "answerType": mode})
            band = item["difficulty"]["overallBand"]
            key = (task, mode, band)
            if key not in buckets:
                buckets[key] = (seed, item)
    # Stable ordering: by task order in COMBOS, then mode, then band.
    order = {tm: i for i, tm in enumerate(COMBOS)}
    return sorted(buckets.items(), key=lambda kv: (order[(kv[0][0], kv[0][1])], kv[0][2]))


def build() -> None:
    os.makedirs(REVIEW_DIR, exist_ok=True)
    misc = load_misconceptions()
    reps = pick_representatives()

    pack = {
        "generatorId": seq.GENERATOR_ID,
        "generatorVersion": seq.GENERATOR_VERSION,
        "note": "Representative items for curriculum review. None is approved or published; "
                "advancing lifecycle state beyond machine-validated is the curriculum authority's decision.",
        "items": [],
    }

    for (task, mode, band), (seed, item) in reps:
        validation = seq.validate(item)
        distractors = []
        for d in item.get("distractors", []):
            mid = d.get("misconceptionId")
            m = misc.get(mid, {})
            distractors.append({
                "value": d["value"],
                "misconceptionId": mid,
                "misconception": m.get("title", ""),
                "whyAStudentPicksIt": m.get("observableError", ""),
                "feedback": m.get("feedback", ""),
            })
        pack["items"].append({
            "seed": seed,
            "mode": mode,
            "task": task,
            "difficultyBand": band,
            "objectiveIds": item["objectiveIds"],
            "params": item["params"],
            "calculatorPolicy": item["calculatorPolicy"],
            "prompt": [b.get("text", "") for b in item["prompt"]["blocks"]],
            "canonicalAnswer": item["answer"]["canonical"],
            "workedSolution": item["solution"]["steps"],
            "distractors": distractors,
            "validation": validation["status"],
            "validationChecks": [c["name"] for c in validation["checks"]],
        })

    json_path = os.path.join(REVIEW_DIR, "arithmetic_sequences_review_pack.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(pack, fh, indent=2)

    # Markdown
    lines = [
        "# Curriculum-Review Pack — Arithmetic Sequences",
        "",
        f"Generator: `{seq.GENERATOR_ID}` v`{seq.GENERATOR_VERSION}`. "
        f"Generated by `oracle/make_review_pack.py`.",
        "",
        "> **Review purpose.** These items are machine-validated. Advancing any item to "
        "`curriculum-reviewed` / `approved` / `published` is the curriculum authority's decision; "
        "this tool never does so. Please review wording, difficulty-band fit, and distractor pedagogy.",
        "",
        f"**Coverage:** {len(pack['items'])} representative items across "
        f"{len(COMBOS)} supported (task, mode) combinations and the difficulty bands that occur.",
        "",
        "| # | Task | Mode | Band | Seed | Answer | Validation |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for i, it in enumerate(pack["items"], 1):
        lines.append(f"| {i} | {it['task']} | {it['mode']} | {it['difficultyBand']} | "
                     f"{it['seed']} | {it['canonicalAnswer']} | {it['validation']} |")
    lines.append("")

    for i, it in enumerate(pack["items"], 1):
        lines += [
            f"## {i}. {it['task']} · {it['mode']} · band {it['difficultyBand']}",
            "",
            f"- **Objective:** `{it['objectiveIds'][0]}`",
            f"- **Seed:** `{it['seed']}`  ·  **Parameters:** `{json.dumps(it['params'])}`  ·  "
            f"**Calculator:** {it['calculatorPolicy']}",
            f"- **Reproduce:** `generate(seed={it['seed']}, {{ task: \"{it['task']}\", "
            f"answerType: \"{it['mode']}\" }})` on `{seq.GENERATOR_ID}` v`{seq.GENERATOR_VERSION}`",
            "",
            "**Question**",
            "",
        ]
        for p in it["prompt"]:
            lines.append(f"> {p}")
        lines.append("")
        lines.append(f"**Canonical answer:** `{it['canonicalAnswer']}`")
        lines.append("")
        lines.append("**Worked solution**")
        lines.append("")
        for s in it["workedSolution"]:
            bit = s.get("ruleOrTheorem") or s.get("intermediateResult") or ""
            lines.append(f"{s['number']}. {s.get('transformation','')} — `{bit}`")
        lines.append("")
        if it["distractors"]:
            lines.append("**Distractors (each from a named misconception)**")
            lines.append("")
            lines.append("| Value | Misconception | Why a student picks it | Feedback |")
            lines.append("| --- | --- | --- | --- |")
            for d in it["distractors"]:
                lines.append(f"| {d['value']} | {d['misconception']} (`{d['misconceptionId']}`) | "
                             f"{d['whyAStudentPicksIt']} | {d['feedback']} |")
            lines.append("")
        lines.append(f"**Validation:** {it['validation']} — checks: "
                     f"{', '.join('`'+c+'`' for c in it['validationChecks'])}")
        lines.append("")
        lines.append("**Curriculum decision:** ☐ approve  ☐ revise  ☐ reject — notes: ____")
        lines.append("")
        lines.append("---")
        lines.append("")

    md_path = os.path.join(REVIEW_DIR, "arithmetic_sequences_review_pack.md")
    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"Review pack: {len(pack['items'])} items")
    print(f"  {os.path.relpath(json_path, ROOT)}")
    print(f"  {os.path.relpath(md_path, ROOT)}")


if __name__ == "__main__":
    build()
