/**
 * Build-time schema compiler.
 *
 * Precompiles the JSON Schemas (the single source of truth) into STANDALONE
 * validator modules using Ajv. The generated modules contain no runtime code
 * generation (no `new Function`/`eval`), so the offline single-file app bundles a
 * plain validator with zero CDN/network dependency and no CSP-unsafe eval.
 *
 * Ajv is a DEV/BUILD-only dependency: the app and tests import the generated
 * validators, never Ajv itself.
 *
 * Run:  node scripts/compile-schemas.mjs   (also part of build:studio)
 */

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, "core", "schema", "compiled");
mkdirSync(outDir, { recursive: true });

// Schemas to precompile: [schema file, output module, export-friendly name].
const TARGETS = [
  { schema: "schemas/question-item.schema.json", out: "question-item.validator.mjs" },
];

for (const t of TARGETS) {
  const schema = JSON.parse(readFileSync(join(root, t.schema), "utf8"));
  // strict:false — the schemas use annotation keywords (version, $comment, examples,
  // format) that are not validation keywords; do not treat them as errors.
  const ajv = new Ajv2020({ code: { source: true, esm: true }, allErrors: true, strict: false });
  const validate = ajv.compile(schema);
  const code = standaloneCode(ajv, validate);
  const header =
    `// GENERATED by scripts/compile-schemas.mjs from ${t.schema}. DO NOT EDIT.\n` +
    `// Regenerate with: node scripts/compile-schemas.mjs\n`;
  writeFileSync(join(outDir, t.out), header + code);
  console.log(`compiled ${t.schema} -> core/schema/compiled/${t.out}`);
}
